// Generated by CIRCT firtool-1.61.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for prints and assertions.

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module PE_64(
  input         clock,
  input  [7:0]  io_in_a,	// @[generators/gemmini/src/main/scala/gemmini/PE.scala:35:14]
  input  [19:0] io_in_b,	// @[generators/gemmini/src/main/scala/gemmini/PE.scala:35:14]
                io_in_d,	// @[generators/gemmini/src/main/scala/gemmini/PE.scala:35:14]
  output [7:0]  io_out_a,	// @[generators/gemmini/src/main/scala/gemmini/PE.scala:35:14]
  output [19:0] io_out_b,	// @[generators/gemmini/src/main/scala/gemmini/PE.scala:35:14]
                io_out_c,	// @[generators/gemmini/src/main/scala/gemmini/PE.scala:35:14]
  input         io_in_control_dataflow,	// @[generators/gemmini/src/main/scala/gemmini/PE.scala:35:14]
                io_in_control_propagate,	// @[generators/gemmini/src/main/scala/gemmini/PE.scala:35:14]
  output        io_out_control_dataflow,	// @[generators/gemmini/src/main/scala/gemmini/PE.scala:35:14]
                io_out_control_propagate,	// @[generators/gemmini/src/main/scala/gemmini/PE.scala:35:14]
  input  [2:0]  io_in_id,	// @[generators/gemmini/src/main/scala/gemmini/PE.scala:35:14]
  output [2:0]  io_out_id,	// @[generators/gemmini/src/main/scala/gemmini/PE.scala:35:14]
  input         io_in_last,	// @[generators/gemmini/src/main/scala/gemmini/PE.scala:35:14]
  output        io_out_last,	// @[generators/gemmini/src/main/scala/gemmini/PE.scala:35:14]
  input         io_in_valid,	// @[generators/gemmini/src/main/scala/gemmini/PE.scala:35:14]
  output        io_out_valid	// @[generators/gemmini/src/main/scala/gemmini/PE.scala:35:14]
);

  reg [7:0] c1;	// @[generators/gemmini/src/main/scala/gemmini/PE.scala:70:15]
  reg [7:0] c2;	// @[generators/gemmini/src/main/scala/gemmini/PE.scala:71:15]
  always @(posedge clock) begin
    if (io_in_valid & io_in_control_propagate)	// @[generators/gemmini/src/main/scala/gemmini/PE.scala:102:95, :141:17, :142:8]
      c1 <= io_in_d[7:0];	// @[generators/gemmini/src/main/scala/gemmini/PE.scala:70:15, :124:10]
    if (~(~io_in_valid | io_in_control_propagate))	// @[generators/gemmini/src/main/scala/gemmini/PE.scala:71:15, :102:95, :119:30, :130:10, :141:{9,17}, :143:8]
      c2 <= io_in_d[7:0];	// @[generators/gemmini/src/main/scala/gemmini/PE.scala:71:15, :124:10]
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:0];
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;
        c1 = _RANDOM[/*Zero width*/ 1'b0][7:0];	// @[generators/gemmini/src/main/scala/gemmini/PE.scala:70:15]
        c2 = _RANDOM[/*Zero width*/ 1'b0][15:8];	// @[generators/gemmini/src/main/scala/gemmini/PE.scala:70:15, :71:15]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  MacUnit mac_unit (	// @[generators/gemmini/src/main/scala/gemmini/PE.scala:64:24]
    .io_in_a  (io_in_a),
    .io_in_b  (io_in_control_propagate ? c2 : c1),	// @[generators/gemmini/src/main/scala/gemmini/PE.scala:70:15, :71:15, :119:30, :121:24, :127:24]
    .io_in_c  (io_in_b),
    .io_out_d (io_out_b)
  );
  assign io_out_a = io_in_a;
  assign io_out_c = io_in_control_propagate ? {{12{c1[7]}}, c1} : {{12{c2[7]}}, c2};	// @[generators/gemmini/src/main/scala/gemmini/PE.scala:70:15, :71:15, :119:30, :120:16, :126:16]
  assign io_out_control_dataflow = io_in_control_dataflow;
  assign io_out_control_propagate = io_in_control_propagate;
  assign io_out_id = io_in_id;
  assign io_out_last = io_in_last;
  assign io_out_valid = io_in_valid;
endmodule

