// Generated by CIRCT firtool-1.61.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for prints and assertions.

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module Pipeline(
  output        io_in_ready,	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:7:14]
  input         io_in_valid,	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:7:14]
  input  [31:0] io_in_bits_out_0,	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:7:14]
                io_in_bits_out_1,	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:7:14]
                io_in_bits_out_2,	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:7:14]
                io_in_bits_out_3,	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:7:14]
                io_in_bits_out_4,	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:7:14]
                io_in_bits_out_5,	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:7:14]
                io_in_bits_out_6,	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:7:14]
                io_in_bits_out_7,	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:7:14]
  input  [15:0] io_in_bits_row,	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:7:14]
  input         io_in_bits_last,	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:7:14]
  input  [12:0] io_in_bits_tag_addr,	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:7:14]
  input         io_in_bits_tag_mask_0,	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:7:14]
                io_in_bits_tag_mask_1,	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:7:14]
                io_in_bits_tag_mask_2,	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:7:14]
                io_in_bits_tag_mask_3,	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:7:14]
                io_in_bits_tag_mask_4,	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:7:14]
                io_in_bits_tag_mask_5,	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:7:14]
                io_in_bits_tag_mask_6,	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:7:14]
                io_in_bits_tag_mask_7,	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:7:14]
                io_in_bits_tag_mask_8,	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:7:14]
                io_in_bits_tag_mask_9,	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:7:14]
                io_in_bits_tag_mask_10,	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:7:14]
                io_in_bits_tag_mask_11,	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:7:14]
                io_in_bits_tag_mask_12,	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:7:14]
                io_in_bits_tag_mask_13,	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:7:14]
                io_in_bits_tag_mask_14,	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:7:14]
                io_in_bits_tag_mask_15,	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:7:14]
                io_in_bits_tag_mask_16,	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:7:14]
                io_in_bits_tag_mask_17,	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:7:14]
                io_in_bits_tag_mask_18,	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:7:14]
                io_in_bits_tag_mask_19,	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:7:14]
                io_in_bits_tag_mask_20,	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:7:14]
                io_in_bits_tag_mask_21,	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:7:14]
                io_in_bits_tag_mask_22,	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:7:14]
                io_in_bits_tag_mask_23,	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:7:14]
                io_in_bits_tag_mask_24,	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:7:14]
                io_in_bits_tag_mask_25,	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:7:14]
                io_in_bits_tag_mask_26,	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:7:14]
                io_in_bits_tag_mask_27,	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:7:14]
                io_in_bits_tag_mask_28,	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:7:14]
                io_in_bits_tag_mask_29,	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:7:14]
                io_in_bits_tag_mask_30,	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:7:14]
                io_in_bits_tag_mask_31,	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:7:14]
                io_in_bits_tag_is_acc,	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:7:14]
                io_in_bits_tag_accumulate,	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:7:14]
  input  [7:0]  io_in_bits_tag_bytes_read,	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:7:14]
                io_in_bits_tag_cmd_id,	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:7:14]
  input         io_out_ready,	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:7:14]
  output        io_out_valid,	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:7:14]
  output [31:0] io_out_bits_out_0,	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:7:14]
                io_out_bits_out_1,	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:7:14]
                io_out_bits_out_2,	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:7:14]
                io_out_bits_out_3,	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:7:14]
                io_out_bits_out_4,	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:7:14]
                io_out_bits_out_5,	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:7:14]
                io_out_bits_out_6,	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:7:14]
                io_out_bits_out_7,	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:7:14]
  output [15:0] io_out_bits_row,	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:7:14]
  output        io_out_bits_last,	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:7:14]
  output [12:0] io_out_bits_tag_addr,	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:7:14]
  output        io_out_bits_tag_mask_0,	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:7:14]
                io_out_bits_tag_mask_1,	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:7:14]
                io_out_bits_tag_mask_2,	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:7:14]
                io_out_bits_tag_mask_3,	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:7:14]
                io_out_bits_tag_mask_4,	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:7:14]
                io_out_bits_tag_mask_5,	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:7:14]
                io_out_bits_tag_mask_6,	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:7:14]
                io_out_bits_tag_mask_7,	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:7:14]
                io_out_bits_tag_mask_8,	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:7:14]
                io_out_bits_tag_mask_9,	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:7:14]
                io_out_bits_tag_mask_10,	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:7:14]
                io_out_bits_tag_mask_11,	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:7:14]
                io_out_bits_tag_mask_12,	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:7:14]
                io_out_bits_tag_mask_13,	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:7:14]
                io_out_bits_tag_mask_14,	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:7:14]
                io_out_bits_tag_mask_15,	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:7:14]
                io_out_bits_tag_mask_16,	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:7:14]
                io_out_bits_tag_mask_17,	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:7:14]
                io_out_bits_tag_mask_18,	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:7:14]
                io_out_bits_tag_mask_19,	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:7:14]
                io_out_bits_tag_mask_20,	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:7:14]
                io_out_bits_tag_mask_21,	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:7:14]
                io_out_bits_tag_mask_22,	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:7:14]
                io_out_bits_tag_mask_23,	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:7:14]
                io_out_bits_tag_mask_24,	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:7:14]
                io_out_bits_tag_mask_25,	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:7:14]
                io_out_bits_tag_mask_26,	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:7:14]
                io_out_bits_tag_mask_27,	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:7:14]
                io_out_bits_tag_mask_28,	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:7:14]
                io_out_bits_tag_mask_29,	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:7:14]
                io_out_bits_tag_mask_30,	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:7:14]
                io_out_bits_tag_mask_31,	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:7:14]
                io_out_bits_tag_is_acc,	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:7:14]
                io_out_bits_tag_accumulate,	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:7:14]
  output [7:0]  io_out_bits_tag_bytes_read,	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:7:14]
                io_out_bits_tag_cmd_id	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:7:14]
);

  assign io_in_ready = io_out_ready;
  assign io_out_valid = io_in_valid;
  assign io_out_bits_out_0 = io_in_bits_out_0;
  assign io_out_bits_out_1 = io_in_bits_out_1;
  assign io_out_bits_out_2 = io_in_bits_out_2;
  assign io_out_bits_out_3 = io_in_bits_out_3;
  assign io_out_bits_out_4 = io_in_bits_out_4;
  assign io_out_bits_out_5 = io_in_bits_out_5;
  assign io_out_bits_out_6 = io_in_bits_out_6;
  assign io_out_bits_out_7 = io_in_bits_out_7;
  assign io_out_bits_row = io_in_bits_row;
  assign io_out_bits_last = io_in_bits_last;
  assign io_out_bits_tag_addr = io_in_bits_tag_addr;
  assign io_out_bits_tag_mask_0 = io_in_bits_tag_mask_0;
  assign io_out_bits_tag_mask_1 = io_in_bits_tag_mask_1;
  assign io_out_bits_tag_mask_2 = io_in_bits_tag_mask_2;
  assign io_out_bits_tag_mask_3 = io_in_bits_tag_mask_3;
  assign io_out_bits_tag_mask_4 = io_in_bits_tag_mask_4;
  assign io_out_bits_tag_mask_5 = io_in_bits_tag_mask_5;
  assign io_out_bits_tag_mask_6 = io_in_bits_tag_mask_6;
  assign io_out_bits_tag_mask_7 = io_in_bits_tag_mask_7;
  assign io_out_bits_tag_mask_8 = io_in_bits_tag_mask_8;
  assign io_out_bits_tag_mask_9 = io_in_bits_tag_mask_9;
  assign io_out_bits_tag_mask_10 = io_in_bits_tag_mask_10;
  assign io_out_bits_tag_mask_11 = io_in_bits_tag_mask_11;
  assign io_out_bits_tag_mask_12 = io_in_bits_tag_mask_12;
  assign io_out_bits_tag_mask_13 = io_in_bits_tag_mask_13;
  assign io_out_bits_tag_mask_14 = io_in_bits_tag_mask_14;
  assign io_out_bits_tag_mask_15 = io_in_bits_tag_mask_15;
  assign io_out_bits_tag_mask_16 = io_in_bits_tag_mask_16;
  assign io_out_bits_tag_mask_17 = io_in_bits_tag_mask_17;
  assign io_out_bits_tag_mask_18 = io_in_bits_tag_mask_18;
  assign io_out_bits_tag_mask_19 = io_in_bits_tag_mask_19;
  assign io_out_bits_tag_mask_20 = io_in_bits_tag_mask_20;
  assign io_out_bits_tag_mask_21 = io_in_bits_tag_mask_21;
  assign io_out_bits_tag_mask_22 = io_in_bits_tag_mask_22;
  assign io_out_bits_tag_mask_23 = io_in_bits_tag_mask_23;
  assign io_out_bits_tag_mask_24 = io_in_bits_tag_mask_24;
  assign io_out_bits_tag_mask_25 = io_in_bits_tag_mask_25;
  assign io_out_bits_tag_mask_26 = io_in_bits_tag_mask_26;
  assign io_out_bits_tag_mask_27 = io_in_bits_tag_mask_27;
  assign io_out_bits_tag_mask_28 = io_in_bits_tag_mask_28;
  assign io_out_bits_tag_mask_29 = io_in_bits_tag_mask_29;
  assign io_out_bits_tag_mask_30 = io_in_bits_tag_mask_30;
  assign io_out_bits_tag_mask_31 = io_in_bits_tag_mask_31;
  assign io_out_bits_tag_is_acc = io_in_bits_tag_is_acc;
  assign io_out_bits_tag_accumulate = io_in_bits_tag_accumulate;
  assign io_out_bits_tag_bytes_read = io_in_bits_tag_bytes_read;
  assign io_out_bits_tag_cmd_id = io_in_bits_tag_cmd_id;
endmodule

