// Generated by CIRCT firtool-1.61.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for prints and assertions.

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module StreamReader(
  input          clock,
                 reset,
                 auto_core_out_a_ready,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output         auto_core_out_a_valid,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [2:0]   auto_core_out_a_bits_opcode,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                 auto_core_out_a_bits_param,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [3:0]   auto_core_out_a_bits_size,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [2:0]   auto_core_out_a_bits_source,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [31:0]  auto_core_out_a_bits_address,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [7:0]   auto_core_out_a_bits_mask,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [63:0]  auto_core_out_a_bits_data,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output         auto_core_out_a_bits_corrupt,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                 auto_core_out_d_ready,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input          auto_core_out_d_valid,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [2:0]   auto_core_out_d_bits_opcode,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [3:0]   auto_core_out_d_bits_size,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [2:0]   auto_core_out_d_bits_source,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [63:0]  auto_core_out_d_bits_data,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output         io_req_ready,	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:63:16]
  input          io_req_valid,	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:63:16]
  input  [33:0]  io_req_bits_vaddr,	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:63:16]
  input  [12:0]  io_req_bits_spaddr,	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:63:16]
  input          io_req_bits_is_acc,	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:63:16]
                 io_req_bits_accumulate,	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:63:16]
                 io_req_bits_has_acc_bitwidth,	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:63:16]
  input  [31:0]  io_req_bits_scale,	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:63:16]
  input          io_req_bits_status_debug,	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:63:16]
                 io_req_bits_status_cease,	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:63:16]
                 io_req_bits_status_wfi,	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:63:16]
  input  [31:0]  io_req_bits_status_isa,	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:63:16]
  input  [1:0]   io_req_bits_status_dprv,	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:63:16]
  input          io_req_bits_status_dv,	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:63:16]
  input  [1:0]   io_req_bits_status_prv,	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:63:16]
  input          io_req_bits_status_v,	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:63:16]
                 io_req_bits_status_sd,	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:63:16]
  input  [22:0]  io_req_bits_status_zero2,	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:63:16]
  input          io_req_bits_status_mpv,	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:63:16]
                 io_req_bits_status_gva,	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:63:16]
                 io_req_bits_status_mbe,	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:63:16]
                 io_req_bits_status_sbe,	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:63:16]
  input  [1:0]   io_req_bits_status_sxl,	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:63:16]
                 io_req_bits_status_uxl,	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:63:16]
  input          io_req_bits_status_sd_rv32,	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:63:16]
  input  [7:0]   io_req_bits_status_zero1,	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:63:16]
  input          io_req_bits_status_tsr,	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:63:16]
                 io_req_bits_status_tw,	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:63:16]
                 io_req_bits_status_tvm,	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:63:16]
                 io_req_bits_status_mxr,	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:63:16]
                 io_req_bits_status_sum,	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:63:16]
                 io_req_bits_status_mprv,	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:63:16]
  input  [1:0]   io_req_bits_status_xs,	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:63:16]
                 io_req_bits_status_fs,	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:63:16]
                 io_req_bits_status_mpp,	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:63:16]
                 io_req_bits_status_vs,	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:63:16]
  input          io_req_bits_status_spp,	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:63:16]
                 io_req_bits_status_mpie,	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:63:16]
                 io_req_bits_status_ube,	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:63:16]
                 io_req_bits_status_spie,	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:63:16]
                 io_req_bits_status_upie,	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:63:16]
                 io_req_bits_status_mie,	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:63:16]
                 io_req_bits_status_hie,	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:63:16]
                 io_req_bits_status_sie,	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:63:16]
                 io_req_bits_status_uie,	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:63:16]
  input  [15:0]  io_req_bits_len,	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:63:16]
                 io_req_bits_repeats,	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:63:16]
  input  [7:0]   io_req_bits_pixel_repeats,	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:63:16]
  input  [15:0]  io_req_bits_block_stride,	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:63:16]
  input  [7:0]   io_req_bits_cmd_id,	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:63:16]
  input          io_resp_ready,	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:63:16]
  output         io_resp_valid,	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:63:16]
  output [255:0] io_resp_bits_data,	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:63:16]
  output [12:0]  io_resp_bits_addr,	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:63:16]
  output         io_resp_bits_mask_0,	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:63:16]
                 io_resp_bits_mask_1,	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:63:16]
                 io_resp_bits_mask_2,	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:63:16]
                 io_resp_bits_mask_3,	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:63:16]
                 io_resp_bits_mask_4,	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:63:16]
                 io_resp_bits_mask_5,	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:63:16]
                 io_resp_bits_mask_6,	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:63:16]
                 io_resp_bits_mask_7,	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:63:16]
                 io_resp_bits_mask_8,	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:63:16]
                 io_resp_bits_mask_9,	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:63:16]
                 io_resp_bits_mask_10,	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:63:16]
                 io_resp_bits_mask_11,	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:63:16]
                 io_resp_bits_mask_12,	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:63:16]
                 io_resp_bits_mask_13,	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:63:16]
                 io_resp_bits_mask_14,	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:63:16]
                 io_resp_bits_mask_15,	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:63:16]
                 io_resp_bits_mask_16,	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:63:16]
                 io_resp_bits_mask_17,	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:63:16]
                 io_resp_bits_mask_18,	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:63:16]
                 io_resp_bits_mask_19,	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:63:16]
                 io_resp_bits_mask_20,	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:63:16]
                 io_resp_bits_mask_21,	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:63:16]
                 io_resp_bits_mask_22,	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:63:16]
                 io_resp_bits_mask_23,	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:63:16]
                 io_resp_bits_mask_24,	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:63:16]
                 io_resp_bits_mask_25,	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:63:16]
                 io_resp_bits_mask_26,	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:63:16]
                 io_resp_bits_mask_27,	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:63:16]
                 io_resp_bits_mask_28,	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:63:16]
                 io_resp_bits_mask_29,	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:63:16]
                 io_resp_bits_mask_30,	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:63:16]
                 io_resp_bits_mask_31,	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:63:16]
                 io_resp_bits_is_acc,	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:63:16]
                 io_resp_bits_accumulate,	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:63:16]
                 io_resp_bits_has_acc_bitwidth,	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:63:16]
  output [31:0]  io_resp_bits_scale,	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:63:16]
  output [15:0]  io_resp_bits_repeats,	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:63:16]
                 io_resp_bits_pixel_repeats,	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:63:16]
                 io_resp_bits_len,	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:63:16]
  output         io_resp_bits_last,	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:63:16]
  output [7:0]   io_resp_bits_bytes_read,	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:63:16]
                 io_resp_bits_cmd_id,	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:63:16]
  output         io_tlb_req_valid,	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:63:16]
  output [33:0]  io_tlb_req_bits_tlb_req_vaddr,	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:63:16]
  output         io_tlb_req_bits_status_debug,	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:63:16]
                 io_tlb_req_bits_status_mxr,	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:63:16]
  input          io_tlb_resp_miss,	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:63:16]
  input  [31:0]  io_tlb_resp_paddr,	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:63:16]
  output         io_busy,	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:63:16]
                 io_counter_event_signal_18,	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:63:16]
                 io_counter_event_signal_19,	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:63:16]
                 io_counter_event_signal_20,	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:63:16]
  output [31:0]  io_counter_external_values_4,	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:63:16]
                 io_counter_external_values_6,	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:63:16]
  input          io_counter_external_reset	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:63:16]
);

  wire        _beatPacker_io_req_ready;	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:77:28]
  wire        _beatPacker_io_in_ready;	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:77:28]
  wire        _xactTracker_io_alloc_ready;	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:75:29]
  wire [2:0]  _xactTracker_io_alloc_xactid;	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:75:29]
  wire [5:0]  _xactTracker_io_peek_entry_shift;	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:75:29]
  wire [12:0] _xactTracker_io_peek_entry_addr;	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:75:29]
  wire        _xactTracker_io_peek_entry_is_acc;	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:75:29]
  wire        _xactTracker_io_peek_entry_accumulate;	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:75:29]
  wire        _xactTracker_io_peek_entry_has_acc_bitwidth;	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:75:29]
  wire [31:0] _xactTracker_io_peek_entry_scale;	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:75:29]
  wire [15:0] _xactTracker_io_peek_entry_repeats;	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:75:29]
  wire [7:0]  _xactTracker_io_peek_entry_pixel_repeats;	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:75:29]
  wire [15:0] _xactTracker_io_peek_entry_len;	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:75:29]
  wire [15:0] _xactTracker_io_peek_entry_block_stride;	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:75:29]
  wire [7:0]  _xactTracker_io_peek_entry_spad_row_offset;	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:75:29]
  wire [6:0]  _xactTracker_io_peek_entry_bytes_to_read;	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:75:29]
  wire        _xactTracker_io_peek_entry_cmd_id;	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:75:29]
  wire        _core_io_reserve_valid;	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:57:24]
  wire [5:0]  _core_io_reserve_entry_shift;	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:57:24]
  wire [12:0] _core_io_reserve_entry_addr;	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:57:24]
  wire        _core_io_reserve_entry_is_acc;	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:57:24]
  wire        _core_io_reserve_entry_accumulate;	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:57:24]
  wire        _core_io_reserve_entry_has_acc_bitwidth;	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:57:24]
  wire [31:0] _core_io_reserve_entry_scale;	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:57:24]
  wire [15:0] _core_io_reserve_entry_repeats;	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:57:24]
  wire [7:0]  _core_io_reserve_entry_pixel_repeats;	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:57:24]
  wire [15:0] _core_io_reserve_entry_len;	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:57:24]
  wire [15:0] _core_io_reserve_entry_block_stride;	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:57:24]
  wire [7:0]  _core_io_reserve_entry_spad_row_offset;	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:57:24]
  wire [6:0]  _core_io_reserve_entry_bytes_to_read;	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:57:24]
  wire        _core_io_reserve_entry_cmd_id;	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:57:24]
  wire        _core_io_beatData_valid;	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:57:24]
  wire [2:0]  _core_io_beatData_bits_xactid;	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:57:24]
  wire [63:0] _core_io_beatData_bits_data;	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:57:24]
  wire [2:0]  _core_io_beatData_bits_lg_len_req;	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:57:24]
  wire        _core_io_beatData_bits_last;	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:57:24]
  wire        _io_resp_bits_bytes_read_T = _beatPacker_io_req_ready & _core_io_beatData_valid;	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:57:24, :77:28, src/main/scala/chisel3/util/Decoupled.scala:52:35]
  reg  [2:0]  xactTracker_io_peek_xactid_buf;	// @[generators/gemmini/src/main/scala/gemmini/Util.scala:90:24]
  reg  [31:0] io_resp_bits_scale_r;	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:103:36]
  reg  [15:0] io_resp_bits_repeats_r;	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:104:38]
  reg  [7:0]  io_resp_bits_pixel_repeats_r;	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:105:44]
  reg  [15:0] io_resp_bits_len_r;	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:106:34]
  reg         io_resp_bits_cmd_id_r;	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:107:37]
  reg  [6:0]  io_resp_bits_bytes_read_r;	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:108:41]
  always @(posedge clock) begin
    if (_io_resp_bits_bytes_read_T) begin	// @[src/main/scala/chisel3/util/Decoupled.scala:52:35]
      xactTracker_io_peek_xactid_buf <= _core_io_beatData_bits_xactid;	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:57:24, generators/gemmini/src/main/scala/gemmini/Util.scala:90:24]
      io_resp_bits_scale_r <= _xactTracker_io_peek_entry_scale;	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:75:29, :103:36]
      io_resp_bits_repeats_r <= _xactTracker_io_peek_entry_repeats;	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:75:29, :104:38]
      io_resp_bits_pixel_repeats_r <= _xactTracker_io_peek_entry_pixel_repeats;	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:75:29, :105:44]
      io_resp_bits_len_r <= _xactTracker_io_peek_entry_len;	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:75:29, :106:34]
      io_resp_bits_cmd_id_r <= _xactTracker_io_peek_entry_cmd_id;	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:75:29, :107:37]
      io_resp_bits_bytes_read_r <= _xactTracker_io_peek_entry_bytes_to_read;	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:75:29, :108:41]
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:2];
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        for (logic [1:0] i = 2'h0; i < 2'h3; i += 2'h1) begin
          _RANDOM[i] = `RANDOM;
        end
        xactTracker_io_peek_xactid_buf = _RANDOM[2'h0][2:0];	// @[generators/gemmini/src/main/scala/gemmini/Util.scala:90:24]
        io_resp_bits_scale_r = {_RANDOM[2'h0][31:3], _RANDOM[2'h1][2:0]};	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:103:36, generators/gemmini/src/main/scala/gemmini/Util.scala:90:24]
        io_resp_bits_repeats_r = _RANDOM[2'h1][18:3];	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:103:36, :104:38]
        io_resp_bits_pixel_repeats_r = _RANDOM[2'h1][26:19];	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:103:36, :105:44]
        io_resp_bits_len_r = {_RANDOM[2'h1][31:27], _RANDOM[2'h2][10:0]};	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:103:36, :106:34]
        io_resp_bits_cmd_id_r = _RANDOM[2'h2][11];	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:106:34, :107:37]
        io_resp_bits_bytes_read_r = _RANDOM[2'h2][18:12];	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:106:34, :108:41]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  StreamReaderCore core (	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:57:24]
    .clock                             (clock),
    .reset                             (reset),
    .auto_out_a_ready                  (auto_core_out_a_ready),
    .auto_out_a_valid                  (auto_core_out_a_valid),
    .auto_out_a_bits_opcode            (auto_core_out_a_bits_opcode),
    .auto_out_a_bits_param             (auto_core_out_a_bits_param),
    .auto_out_a_bits_size              (auto_core_out_a_bits_size),
    .auto_out_a_bits_source            (auto_core_out_a_bits_source),
    .auto_out_a_bits_address           (auto_core_out_a_bits_address),
    .auto_out_a_bits_mask              (auto_core_out_a_bits_mask),
    .auto_out_a_bits_data              (auto_core_out_a_bits_data),
    .auto_out_a_bits_corrupt           (auto_core_out_a_bits_corrupt),
    .auto_out_d_ready                  (auto_core_out_d_ready),
    .auto_out_d_valid                  (auto_core_out_d_valid),
    .auto_out_d_bits_opcode            (auto_core_out_d_bits_opcode),
    .auto_out_d_bits_size              (auto_core_out_d_bits_size),
    .auto_out_d_bits_source            (auto_core_out_d_bits_source),
    .auto_out_d_bits_data              (auto_core_out_d_bits_data),
    .io_req_ready                      (io_req_ready),
    .io_req_valid                      (io_req_valid),
    .io_req_bits_vaddr                 (io_req_bits_vaddr),
    .io_req_bits_spaddr                (io_req_bits_spaddr),
    .io_req_bits_is_acc                (io_req_bits_is_acc),
    .io_req_bits_accumulate            (io_req_bits_accumulate),
    .io_req_bits_has_acc_bitwidth      (io_req_bits_has_acc_bitwidth),
    .io_req_bits_scale                 (io_req_bits_scale),
    .io_req_bits_status_debug          (io_req_bits_status_debug),
    .io_req_bits_status_cease          (io_req_bits_status_cease),
    .io_req_bits_status_wfi            (io_req_bits_status_wfi),
    .io_req_bits_status_isa            (io_req_bits_status_isa),
    .io_req_bits_status_dprv           (io_req_bits_status_dprv),
    .io_req_bits_status_dv             (io_req_bits_status_dv),
    .io_req_bits_status_prv            (io_req_bits_status_prv),
    .io_req_bits_status_v              (io_req_bits_status_v),
    .io_req_bits_status_sd             (io_req_bits_status_sd),
    .io_req_bits_status_zero2          (io_req_bits_status_zero2),
    .io_req_bits_status_mpv            (io_req_bits_status_mpv),
    .io_req_bits_status_gva            (io_req_bits_status_gva),
    .io_req_bits_status_mbe            (io_req_bits_status_mbe),
    .io_req_bits_status_sbe            (io_req_bits_status_sbe),
    .io_req_bits_status_sxl            (io_req_bits_status_sxl),
    .io_req_bits_status_uxl            (io_req_bits_status_uxl),
    .io_req_bits_status_sd_rv32        (io_req_bits_status_sd_rv32),
    .io_req_bits_status_zero1          (io_req_bits_status_zero1),
    .io_req_bits_status_tsr            (io_req_bits_status_tsr),
    .io_req_bits_status_tw             (io_req_bits_status_tw),
    .io_req_bits_status_tvm            (io_req_bits_status_tvm),
    .io_req_bits_status_mxr            (io_req_bits_status_mxr),
    .io_req_bits_status_sum            (io_req_bits_status_sum),
    .io_req_bits_status_mprv           (io_req_bits_status_mprv),
    .io_req_bits_status_xs             (io_req_bits_status_xs),
    .io_req_bits_status_fs             (io_req_bits_status_fs),
    .io_req_bits_status_mpp            (io_req_bits_status_mpp),
    .io_req_bits_status_vs             (io_req_bits_status_vs),
    .io_req_bits_status_spp            (io_req_bits_status_spp),
    .io_req_bits_status_mpie           (io_req_bits_status_mpie),
    .io_req_bits_status_ube            (io_req_bits_status_ube),
    .io_req_bits_status_spie           (io_req_bits_status_spie),
    .io_req_bits_status_upie           (io_req_bits_status_upie),
    .io_req_bits_status_mie            (io_req_bits_status_mie),
    .io_req_bits_status_hie            (io_req_bits_status_hie),
    .io_req_bits_status_sie            (io_req_bits_status_sie),
    .io_req_bits_status_uie            (io_req_bits_status_uie),
    .io_req_bits_len                   (io_req_bits_len),
    .io_req_bits_repeats               (io_req_bits_repeats),
    .io_req_bits_pixel_repeats         (io_req_bits_pixel_repeats),
    .io_req_bits_block_stride          (io_req_bits_block_stride),
    .io_req_bits_cmd_id                (io_req_bits_cmd_id),
    .io_reserve_valid                  (_core_io_reserve_valid),
    .io_reserve_ready                  (_xactTracker_io_alloc_ready),	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:75:29]
    .io_reserve_xactid                 (_xactTracker_io_alloc_xactid),	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:75:29]
    .io_reserve_entry_shift            (_core_io_reserve_entry_shift),
    .io_reserve_entry_addr             (_core_io_reserve_entry_addr),
    .io_reserve_entry_is_acc           (_core_io_reserve_entry_is_acc),
    .io_reserve_entry_accumulate       (_core_io_reserve_entry_accumulate),
    .io_reserve_entry_has_acc_bitwidth (_core_io_reserve_entry_has_acc_bitwidth),
    .io_reserve_entry_scale            (_core_io_reserve_entry_scale),
    .io_reserve_entry_repeats          (_core_io_reserve_entry_repeats),
    .io_reserve_entry_pixel_repeats    (_core_io_reserve_entry_pixel_repeats),
    .io_reserve_entry_len              (_core_io_reserve_entry_len),
    .io_reserve_entry_block_stride     (_core_io_reserve_entry_block_stride),
    .io_reserve_entry_spad_row_offset  (_core_io_reserve_entry_spad_row_offset),
    .io_reserve_entry_bytes_to_read    (_core_io_reserve_entry_bytes_to_read),
    .io_reserve_entry_cmd_id           (_core_io_reserve_entry_cmd_id),
    .io_beatData_ready                 (_beatPacker_io_in_ready),	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:77:28]
    .io_beatData_valid                 (_core_io_beatData_valid),
    .io_beatData_bits_xactid           (_core_io_beatData_bits_xactid),
    .io_beatData_bits_data             (_core_io_beatData_bits_data),
    .io_beatData_bits_lg_len_req       (_core_io_beatData_bits_lg_len_req),
    .io_beatData_bits_last             (_core_io_beatData_bits_last),
    .io_tlb_req_valid                  (io_tlb_req_valid),
    .io_tlb_req_bits_tlb_req_vaddr     (io_tlb_req_bits_tlb_req_vaddr),
    .io_tlb_req_bits_status_debug      (io_tlb_req_bits_status_debug),
    .io_tlb_req_bits_status_mxr        (io_tlb_req_bits_status_mxr),
    .io_tlb_resp_miss                  (io_tlb_resp_miss),
    .io_tlb_resp_paddr                 (io_tlb_resp_paddr),
    .io_counter_event_signal_18        (io_counter_event_signal_18),
    .io_counter_event_signal_19        (io_counter_event_signal_19),
    .io_counter_event_signal_20        (io_counter_event_signal_20),
    .io_counter_external_values_4      (io_counter_external_values_4),
    .io_counter_external_reset         (io_counter_external_reset)
  );
  XactTracker xactTracker (	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:75:29]
    .clock                           (clock),
    .reset                           (reset),
    .io_alloc_valid                  (_core_io_reserve_valid),	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:57:24]
    .io_alloc_ready                  (_xactTracker_io_alloc_ready),
    .io_alloc_xactid                 (_xactTracker_io_alloc_xactid),
    .io_alloc_entry_shift            (_core_io_reserve_entry_shift),	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:57:24]
    .io_alloc_entry_addr             (_core_io_reserve_entry_addr),	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:57:24]
    .io_alloc_entry_is_acc           (_core_io_reserve_entry_is_acc),	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:57:24]
    .io_alloc_entry_accumulate       (_core_io_reserve_entry_accumulate),	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:57:24]
    .io_alloc_entry_has_acc_bitwidth (_core_io_reserve_entry_has_acc_bitwidth),	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:57:24]
    .io_alloc_entry_scale            (_core_io_reserve_entry_scale),	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:57:24]
    .io_alloc_entry_repeats          (_core_io_reserve_entry_repeats),	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:57:24]
    .io_alloc_entry_pixel_repeats    (_core_io_reserve_entry_pixel_repeats),	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:57:24]
    .io_alloc_entry_len              (_core_io_reserve_entry_len),	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:57:24]
    .io_alloc_entry_block_stride     (_core_io_reserve_entry_block_stride),	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:57:24]
    .io_alloc_entry_spad_row_offset  (_core_io_reserve_entry_spad_row_offset),	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:57:24]
    .io_alloc_entry_bytes_to_read    (_core_io_reserve_entry_bytes_to_read),	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:57:24]
    .io_alloc_entry_cmd_id           (_core_io_reserve_entry_cmd_id),	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:57:24]
    .io_peek_xactid                  (_io_resp_bits_bytes_read_T ? _core_io_beatData_bits_xactid : xactTracker_io_peek_xactid_buf),	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:57:24, generators/gemmini/src/main/scala/gemmini/Util.scala:90:24, :91:8, src/main/scala/chisel3/util/Decoupled.scala:52:35]
    .io_peek_pop                     (_beatPacker_io_in_ready & _core_io_beatData_valid & _core_io_beatData_bits_last),	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:57:24, :77:28, :86:54]
    .io_peek_entry_shift             (_xactTracker_io_peek_entry_shift),
    .io_peek_entry_addr              (_xactTracker_io_peek_entry_addr),
    .io_peek_entry_is_acc            (_xactTracker_io_peek_entry_is_acc),
    .io_peek_entry_accumulate        (_xactTracker_io_peek_entry_accumulate),
    .io_peek_entry_has_acc_bitwidth  (_xactTracker_io_peek_entry_has_acc_bitwidth),
    .io_peek_entry_scale             (_xactTracker_io_peek_entry_scale),
    .io_peek_entry_repeats           (_xactTracker_io_peek_entry_repeats),
    .io_peek_entry_pixel_repeats     (_xactTracker_io_peek_entry_pixel_repeats),
    .io_peek_entry_len               (_xactTracker_io_peek_entry_len),
    .io_peek_entry_block_stride      (_xactTracker_io_peek_entry_block_stride),
    .io_peek_entry_spad_row_offset   (_xactTracker_io_peek_entry_spad_row_offset),
    .io_peek_entry_bytes_to_read     (_xactTracker_io_peek_entry_bytes_to_read),
    .io_peek_entry_cmd_id            (_xactTracker_io_peek_entry_cmd_id),
    .io_busy                         (io_busy),
    .io_counter_external_values_6    (io_counter_external_values_6),
    .io_counter_external_reset       (io_counter_external_reset)
  );
  BeatMerger beatPacker (	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:77:28]
    .clock                        (clock),
    .reset                        (reset),
    .io_req_ready                 (_beatPacker_io_req_ready),
    .io_req_valid                 (_core_io_beatData_valid),	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:57:24]
    .io_req_bits_shift            (_xactTracker_io_peek_entry_shift),	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:75:29]
    .io_req_bits_addr             (_xactTracker_io_peek_entry_addr),	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:75:29]
    .io_req_bits_is_acc           (_xactTracker_io_peek_entry_is_acc),	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:75:29]
    .io_req_bits_accumulate       (_xactTracker_io_peek_entry_accumulate),	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:75:29]
    .io_req_bits_has_acc_bitwidth (_xactTracker_io_peek_entry_has_acc_bitwidth),	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:75:29]
    .io_req_bits_block_stride     (_xactTracker_io_peek_entry_block_stride),	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:75:29]
    .io_req_bits_spad_row_offset  (_xactTracker_io_peek_entry_spad_row_offset),	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:75:29]
    .io_req_bits_lg_len_req       (_core_io_beatData_bits_lg_len_req),	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:57:24]
    .io_req_bits_bytes_to_read    (_xactTracker_io_peek_entry_bytes_to_read),	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:75:29]
    .io_in_ready                  (_beatPacker_io_in_ready),
    .io_in_valid                  (_core_io_beatData_valid),	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:57:24]
    .io_in_bits                   (_core_io_beatData_bits_data),	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:57:24]
    .io_out_ready                 (io_resp_ready),
    .io_out_valid                 (io_resp_valid),
    .io_out_bits_data             (io_resp_bits_data),
    .io_out_bits_addr             (io_resp_bits_addr),
    .io_out_bits_is_acc           (io_resp_bits_is_acc),
    .io_out_bits_accumulate       (io_resp_bits_accumulate),
    .io_out_bits_has_acc_bitwidth (io_resp_bits_has_acc_bitwidth),
    .io_out_bits_mask_0           (io_resp_bits_mask_0),
    .io_out_bits_mask_1           (io_resp_bits_mask_1),
    .io_out_bits_mask_2           (io_resp_bits_mask_2),
    .io_out_bits_mask_3           (io_resp_bits_mask_3),
    .io_out_bits_mask_4           (io_resp_bits_mask_4),
    .io_out_bits_mask_5           (io_resp_bits_mask_5),
    .io_out_bits_mask_6           (io_resp_bits_mask_6),
    .io_out_bits_mask_7           (io_resp_bits_mask_7),
    .io_out_bits_mask_8           (io_resp_bits_mask_8),
    .io_out_bits_mask_9           (io_resp_bits_mask_9),
    .io_out_bits_mask_10          (io_resp_bits_mask_10),
    .io_out_bits_mask_11          (io_resp_bits_mask_11),
    .io_out_bits_mask_12          (io_resp_bits_mask_12),
    .io_out_bits_mask_13          (io_resp_bits_mask_13),
    .io_out_bits_mask_14          (io_resp_bits_mask_14),
    .io_out_bits_mask_15          (io_resp_bits_mask_15),
    .io_out_bits_mask_16          (io_resp_bits_mask_16),
    .io_out_bits_mask_17          (io_resp_bits_mask_17),
    .io_out_bits_mask_18          (io_resp_bits_mask_18),
    .io_out_bits_mask_19          (io_resp_bits_mask_19),
    .io_out_bits_mask_20          (io_resp_bits_mask_20),
    .io_out_bits_mask_21          (io_resp_bits_mask_21),
    .io_out_bits_mask_22          (io_resp_bits_mask_22),
    .io_out_bits_mask_23          (io_resp_bits_mask_23),
    .io_out_bits_mask_24          (io_resp_bits_mask_24),
    .io_out_bits_mask_25          (io_resp_bits_mask_25),
    .io_out_bits_mask_26          (io_resp_bits_mask_26),
    .io_out_bits_mask_27          (io_resp_bits_mask_27),
    .io_out_bits_mask_28          (io_resp_bits_mask_28),
    .io_out_bits_mask_29          (io_resp_bits_mask_29),
    .io_out_bits_mask_30          (io_resp_bits_mask_30),
    .io_out_bits_mask_31          (io_resp_bits_mask_31),
    .io_out_bits_last             (io_resp_bits_last)
  );
  assign io_resp_bits_scale = io_resp_bits_scale_r;	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:103:36]
  assign io_resp_bits_repeats = io_resp_bits_repeats_r;	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:104:38]
  assign io_resp_bits_pixel_repeats = {8'h0, io_resp_bits_pixel_repeats_r};	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:105:{32,44}]
  assign io_resp_bits_len = io_resp_bits_len_r;	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:106:34]
  assign io_resp_bits_bytes_read = {1'h0, io_resp_bits_bytes_read_r};	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:108:{29,41}]
  assign io_resp_bits_cmd_id = {7'h0, io_resp_bits_cmd_id_r};	// @[generators/gemmini/src/main/scala/gemmini/DMA.scala:107:{25,37}]
endmodule

