// Generated by CIRCT firtool-1.61.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for prints and assertions.

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module TLB_2(
  input  [33:0] io_req_bits_vaddr,	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:309:14]
  output [31:0] io_resp_paddr,	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:309:14]
  output        io_resp_pf_inst,	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:309:14]
                io_resp_ae_inst,	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:309:14]
                io_resp_cacheable,	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:309:14]
                io_ptw_req_bits_valid,	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:309:14]
  output [20:0] io_ptw_req_bits_bits_addr,	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:309:14]
  output        io_ptw_req_bits_bits_need_gpa,	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:309:14]
                io_ptw_req_bits_bits_vstage1,	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:309:14]
                io_ptw_req_bits_bits_stage2,	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:309:14]
  input         io_ptw_status_debug,	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:309:14]
                io_ptw_pmp_0_cfg_l,	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:309:14]
  input  [1:0]  io_ptw_pmp_0_cfg_a,	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:309:14]
  input         io_ptw_pmp_0_cfg_x,	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:309:14]
  input  [29:0] io_ptw_pmp_0_addr,	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:309:14]
  input  [31:0] io_ptw_pmp_0_mask,	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:309:14]
  input         io_ptw_pmp_1_cfg_l,	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:309:14]
  input  [1:0]  io_ptw_pmp_1_cfg_a,	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:309:14]
  input         io_ptw_pmp_1_cfg_x,	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:309:14]
  input  [29:0] io_ptw_pmp_1_addr,	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:309:14]
  input  [31:0] io_ptw_pmp_1_mask,	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:309:14]
  input         io_ptw_pmp_2_cfg_l,	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:309:14]
  input  [1:0]  io_ptw_pmp_2_cfg_a,	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:309:14]
  input         io_ptw_pmp_2_cfg_x,	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:309:14]
  input  [29:0] io_ptw_pmp_2_addr,	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:309:14]
  input  [31:0] io_ptw_pmp_2_mask,	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:309:14]
  input         io_ptw_pmp_3_cfg_l,	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:309:14]
  input  [1:0]  io_ptw_pmp_3_cfg_a,	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:309:14]
  input         io_ptw_pmp_3_cfg_x,	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:309:14]
  input  [29:0] io_ptw_pmp_3_addr,	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:309:14]
  input  [31:0] io_ptw_pmp_3_mask,	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:309:14]
  input         io_ptw_pmp_4_cfg_l,	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:309:14]
  input  [1:0]  io_ptw_pmp_4_cfg_a,	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:309:14]
  input         io_ptw_pmp_4_cfg_x,	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:309:14]
  input  [29:0] io_ptw_pmp_4_addr,	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:309:14]
  input  [31:0] io_ptw_pmp_4_mask,	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:309:14]
  input         io_ptw_pmp_5_cfg_l,	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:309:14]
  input  [1:0]  io_ptw_pmp_5_cfg_a,	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:309:14]
  input         io_ptw_pmp_5_cfg_x,	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:309:14]
  input  [29:0] io_ptw_pmp_5_addr,	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:309:14]
  input  [31:0] io_ptw_pmp_5_mask,	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:309:14]
  input         io_ptw_pmp_6_cfg_l,	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:309:14]
  input  [1:0]  io_ptw_pmp_6_cfg_a,	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:309:14]
  input         io_ptw_pmp_6_cfg_x,	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:309:14]
  input  [29:0] io_ptw_pmp_6_addr,	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:309:14]
  input  [31:0] io_ptw_pmp_6_mask,	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:309:14]
  input         io_ptw_pmp_7_cfg_l,	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:309:14]
  input  [1:0]  io_ptw_pmp_7_cfg_a,	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:309:14]
  input         io_ptw_pmp_7_cfg_x,	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:309:14]
  input  [29:0] io_ptw_pmp_7_addr,	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:309:14]
  input  [31:0] io_ptw_pmp_7_mask,	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:309:14]
  input         io_kill	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:309:14]
);

  wire        _pmp_io_x;	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:405:19]
  wire [3:0]  _GEN = io_req_bits_vaddr[31:28] ^ 4'h8;	// @[generators/rocket-chip/src/main/scala/diplomacy/Parameters.scala:137:31, generators/rocket-chip/src/main/scala/rocket/TLB.scala:406:15]
  wire [11:0] _GEN_0 = io_req_bits_vaddr[27:16] ^ 12'h800;	// @[generators/rocket-chip/src/main/scala/diplomacy/Parameters.scala:137:31]
  wire        legal_address = {io_req_bits_vaddr[33:14], ~(io_req_bits_vaddr[13:12])} == 22'h0 | {io_req_bits_vaddr[33:26], io_req_bits_vaddr[25:12] ^ 14'h2010} == 22'h0 | {io_req_bits_vaddr[33:13], ~(io_req_bits_vaddr[12])} == 22'h0 | {io_req_bits_vaddr[33:29], io_req_bits_vaddr[28:12] ^ 17'h10020} == 22'h0 | {io_req_bits_vaddr[33:26], io_req_bits_vaddr[25:16] ^ 10'h200} == 18'h0 | {io_req_bits_vaddr[33:28], ~(io_req_bits_vaddr[27:26])} == 8'h0 | ~(|(io_req_bits_vaddr[33:12])) | {io_req_bits_vaddr[33:17], ~(io_req_bits_vaddr[16])} == 18'h0 | {io_req_bits_vaddr[33:21], io_req_bits_vaddr[20:12] ^ 9'h100} == 22'h0 | {io_req_bits_vaddr[33:21], io_req_bits_vaddr[20:12] ^ 9'h110} == 22'h0 | {io_req_bits_vaddr[33:32], _GEN} == 6'h0 | {io_req_bits_vaddr[33:28], _GEN_0} == 18'h0;	// @[generators/rocket-chip/src/main/scala/diplomacy/Parameters.scala:137:{31,41,46,59}, generators/rocket-chip/src/main/scala/rocket/TLB.scala:412:67]
  PMPChecker_3 pmp (	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:405:19]
    .io_prv         (2'h3),	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:309:14]
    .io_pmp_0_cfg_l (io_ptw_pmp_0_cfg_l),
    .io_pmp_0_cfg_a (io_ptw_pmp_0_cfg_a),
    .io_pmp_0_cfg_x (io_ptw_pmp_0_cfg_x),
    .io_pmp_0_addr  (io_ptw_pmp_0_addr),
    .io_pmp_0_mask  (io_ptw_pmp_0_mask),
    .io_pmp_1_cfg_l (io_ptw_pmp_1_cfg_l),
    .io_pmp_1_cfg_a (io_ptw_pmp_1_cfg_a),
    .io_pmp_1_cfg_x (io_ptw_pmp_1_cfg_x),
    .io_pmp_1_addr  (io_ptw_pmp_1_addr),
    .io_pmp_1_mask  (io_ptw_pmp_1_mask),
    .io_pmp_2_cfg_l (io_ptw_pmp_2_cfg_l),
    .io_pmp_2_cfg_a (io_ptw_pmp_2_cfg_a),
    .io_pmp_2_cfg_x (io_ptw_pmp_2_cfg_x),
    .io_pmp_2_addr  (io_ptw_pmp_2_addr),
    .io_pmp_2_mask  (io_ptw_pmp_2_mask),
    .io_pmp_3_cfg_l (io_ptw_pmp_3_cfg_l),
    .io_pmp_3_cfg_a (io_ptw_pmp_3_cfg_a),
    .io_pmp_3_cfg_x (io_ptw_pmp_3_cfg_x),
    .io_pmp_3_addr  (io_ptw_pmp_3_addr),
    .io_pmp_3_mask  (io_ptw_pmp_3_mask),
    .io_pmp_4_cfg_l (io_ptw_pmp_4_cfg_l),
    .io_pmp_4_cfg_a (io_ptw_pmp_4_cfg_a),
    .io_pmp_4_cfg_x (io_ptw_pmp_4_cfg_x),
    .io_pmp_4_addr  (io_ptw_pmp_4_addr),
    .io_pmp_4_mask  (io_ptw_pmp_4_mask),
    .io_pmp_5_cfg_l (io_ptw_pmp_5_cfg_l),
    .io_pmp_5_cfg_a (io_ptw_pmp_5_cfg_a),
    .io_pmp_5_cfg_x (io_ptw_pmp_5_cfg_x),
    .io_pmp_5_addr  (io_ptw_pmp_5_addr),
    .io_pmp_5_mask  (io_ptw_pmp_5_mask),
    .io_pmp_6_cfg_l (io_ptw_pmp_6_cfg_l),
    .io_pmp_6_cfg_a (io_ptw_pmp_6_cfg_a),
    .io_pmp_6_cfg_x (io_ptw_pmp_6_cfg_x),
    .io_pmp_6_addr  (io_ptw_pmp_6_addr),
    .io_pmp_6_mask  (io_ptw_pmp_6_mask),
    .io_pmp_7_cfg_l (io_ptw_pmp_7_cfg_l),
    .io_pmp_7_cfg_a (io_ptw_pmp_7_cfg_a),
    .io_pmp_7_cfg_x (io_ptw_pmp_7_cfg_x),
    .io_pmp_7_addr  (io_ptw_pmp_7_addr),
    .io_pmp_7_mask  (io_ptw_pmp_7_mask),
    .io_addr        (io_req_bits_vaddr[31:0]),	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:406:15]
    .io_x           (_pmp_io_x)
  );
  OptimizationBarrier entries_barrier (	// @[generators/rocket-chip/src/main/scala/util/package.scala:259:25]
    .io_x_u        (1'h0),	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:321:21]
    .io_x_ae_ptw   (1'h0),	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:321:21]
    .io_x_ae_final (1'h0),	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:321:21]
    .io_x_pf       (1'h0),	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:321:21]
    .io_x_gf       (1'h0),	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:321:21]
    .io_x_sw       (1'h0),	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:321:21]
    .io_x_sx       (1'h0),	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:321:21]
    .io_x_sr       (1'h0),	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:321:21]
    .io_x_pw       (1'h0),	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:321:21]
    .io_x_px       (1'h0),	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:321:21]
    .io_x_pr       (1'h0),	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:321:21]
    .io_x_ppp      (1'h0),	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:321:21]
    .io_x_pal      (1'h0),	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:321:21]
    .io_x_paa      (1'h0),	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:321:21]
    .io_x_eff      (1'h0),	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:321:21]
    .io_x_c        (1'h0),	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:321:21]
    .io_y_u        (/* unused */),
    .io_y_ae_ptw   (/* unused */),
    .io_y_ae_final (/* unused */),
    .io_y_pf       (/* unused */),
    .io_y_gf       (/* unused */),
    .io_y_sw       (/* unused */),
    .io_y_sx       (/* unused */),
    .io_y_sr       (/* unused */),
    .io_y_pw       (/* unused */),
    .io_y_px       (/* unused */),
    .io_y_pr       (/* unused */),
    .io_y_ppp      (/* unused */),
    .io_y_pal      (/* unused */),
    .io_y_paa      (/* unused */),
    .io_y_eff      (/* unused */),
    .io_y_c        (/* unused */)
  );
  OptimizationBarrier entries_barrier_1 (	// @[generators/rocket-chip/src/main/scala/util/package.scala:259:25]
    .io_x_u        (1'h0),	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:321:21]
    .io_x_ae_ptw   (1'h0),	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:321:21]
    .io_x_ae_final (1'h0),	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:321:21]
    .io_x_pf       (1'h0),	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:321:21]
    .io_x_gf       (1'h0),	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:321:21]
    .io_x_sw       (1'h0),	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:321:21]
    .io_x_sx       (1'h0),	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:321:21]
    .io_x_sr       (1'h0),	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:321:21]
    .io_x_pw       (1'h0),	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:321:21]
    .io_x_px       (1'h0),	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:321:21]
    .io_x_pr       (1'h0),	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:321:21]
    .io_x_ppp      (1'h0),	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:321:21]
    .io_x_pal      (1'h0),	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:321:21]
    .io_x_paa      (1'h0),	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:321:21]
    .io_x_eff      (1'h0),	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:321:21]
    .io_x_c        (1'h0),	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:321:21]
    .io_y_u        (/* unused */),
    .io_y_ae_ptw   (/* unused */),
    .io_y_ae_final (/* unused */),
    .io_y_pf       (/* unused */),
    .io_y_gf       (/* unused */),
    .io_y_sw       (/* unused */),
    .io_y_sx       (/* unused */),
    .io_y_sr       (/* unused */),
    .io_y_pw       (/* unused */),
    .io_y_px       (/* unused */),
    .io_y_pr       (/* unused */),
    .io_y_ppp      (/* unused */),
    .io_y_pal      (/* unused */),
    .io_y_paa      (/* unused */),
    .io_y_eff      (/* unused */),
    .io_y_c        (/* unused */)
  );
  OptimizationBarrier entries_barrier_2 (	// @[generators/rocket-chip/src/main/scala/util/package.scala:259:25]
    .io_x_u        (1'h0),	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:321:21]
    .io_x_ae_ptw   (1'h0),	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:321:21]
    .io_x_ae_final (1'h0),	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:321:21]
    .io_x_pf       (1'h0),	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:321:21]
    .io_x_gf       (1'h0),	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:321:21]
    .io_x_sw       (1'h0),	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:321:21]
    .io_x_sx       (1'h0),	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:321:21]
    .io_x_sr       (1'h0),	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:321:21]
    .io_x_pw       (1'h0),	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:321:21]
    .io_x_px       (1'h0),	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:321:21]
    .io_x_pr       (1'h0),	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:321:21]
    .io_x_ppp      (1'h0),	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:321:21]
    .io_x_pal      (1'h0),	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:321:21]
    .io_x_paa      (1'h0),	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:321:21]
    .io_x_eff      (1'h0),	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:321:21]
    .io_x_c        (1'h0),	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:321:21]
    .io_y_u        (/* unused */),
    .io_y_ae_ptw   (/* unused */),
    .io_y_ae_final (/* unused */),
    .io_y_pf       (/* unused */),
    .io_y_gf       (/* unused */),
    .io_y_sw       (/* unused */),
    .io_y_sx       (/* unused */),
    .io_y_sr       (/* unused */),
    .io_y_pw       (/* unused */),
    .io_y_px       (/* unused */),
    .io_y_pr       (/* unused */),
    .io_y_ppp      (/* unused */),
    .io_y_pal      (/* unused */),
    .io_y_paa      (/* unused */),
    .io_y_eff      (/* unused */),
    .io_y_c        (/* unused */)
  );
  OptimizationBarrier entries_barrier_3 (	// @[generators/rocket-chip/src/main/scala/util/package.scala:259:25]
    .io_x_u        (1'h0),	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:321:21]
    .io_x_ae_ptw   (1'h0),	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:321:21]
    .io_x_ae_final (1'h0),	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:321:21]
    .io_x_pf       (1'h0),	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:321:21]
    .io_x_gf       (1'h0),	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:321:21]
    .io_x_sw       (1'h0),	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:321:21]
    .io_x_sx       (1'h0),	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:321:21]
    .io_x_sr       (1'h0),	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:321:21]
    .io_x_pw       (1'h0),	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:321:21]
    .io_x_px       (1'h0),	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:321:21]
    .io_x_pr       (1'h0),	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:321:21]
    .io_x_ppp      (1'h0),	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:321:21]
    .io_x_pal      (1'h0),	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:321:21]
    .io_x_paa      (1'h0),	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:321:21]
    .io_x_eff      (1'h0),	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:321:21]
    .io_x_c        (1'h0),	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:321:21]
    .io_y_u        (/* unused */),
    .io_y_ae_ptw   (/* unused */),
    .io_y_ae_final (/* unused */),
    .io_y_pf       (/* unused */),
    .io_y_gf       (/* unused */),
    .io_y_sw       (/* unused */),
    .io_y_sx       (/* unused */),
    .io_y_sr       (/* unused */),
    .io_y_pw       (/* unused */),
    .io_y_px       (/* unused */),
    .io_y_pr       (/* unused */),
    .io_y_ppp      (/* unused */),
    .io_y_pal      (/* unused */),
    .io_y_paa      (/* unused */),
    .io_y_eff      (/* unused */),
    .io_y_c        (/* unused */)
  );
  OptimizationBarrier entries_barrier_4 (	// @[generators/rocket-chip/src/main/scala/util/package.scala:259:25]
    .io_x_u        (1'h0),	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:321:21]
    .io_x_ae_ptw   (1'h0),	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:321:21]
    .io_x_ae_final (1'h0),	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:321:21]
    .io_x_pf       (1'h0),	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:321:21]
    .io_x_gf       (1'h0),	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:321:21]
    .io_x_sw       (1'h0),	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:321:21]
    .io_x_sx       (1'h0),	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:321:21]
    .io_x_sr       (1'h0),	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:321:21]
    .io_x_pw       (1'h0),	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:321:21]
    .io_x_px       (1'h0),	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:321:21]
    .io_x_pr       (1'h0),	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:321:21]
    .io_x_ppp      (1'h0),	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:321:21]
    .io_x_pal      (1'h0),	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:321:21]
    .io_x_paa      (1'h0),	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:321:21]
    .io_x_eff      (1'h0),	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:321:21]
    .io_x_c        (1'h0),	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:321:21]
    .io_y_u        (/* unused */),
    .io_y_ae_ptw   (/* unused */),
    .io_y_ae_final (/* unused */),
    .io_y_pf       (/* unused */),
    .io_y_gf       (/* unused */),
    .io_y_sw       (/* unused */),
    .io_y_sx       (/* unused */),
    .io_y_sr       (/* unused */),
    .io_y_pw       (/* unused */),
    .io_y_px       (/* unused */),
    .io_y_pr       (/* unused */),
    .io_y_ppp      (/* unused */),
    .io_y_pal      (/* unused */),
    .io_y_paa      (/* unused */),
    .io_y_eff      (/* unused */),
    .io_y_c        (/* unused */)
  );
  OptimizationBarrier entries_barrier_5 (	// @[generators/rocket-chip/src/main/scala/util/package.scala:259:25]
    .io_x_u        (1'h0),	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:321:21]
    .io_x_ae_ptw   (1'h0),	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:321:21]
    .io_x_ae_final (1'h0),	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:321:21]
    .io_x_pf       (1'h0),	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:321:21]
    .io_x_gf       (1'h0),	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:321:21]
    .io_x_sw       (1'h0),	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:321:21]
    .io_x_sx       (1'h0),	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:321:21]
    .io_x_sr       (1'h0),	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:321:21]
    .io_x_pw       (1'h0),	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:321:21]
    .io_x_px       (1'h0),	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:321:21]
    .io_x_pr       (1'h0),	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:321:21]
    .io_x_ppp      (1'h0),	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:321:21]
    .io_x_pal      (1'h0),	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:321:21]
    .io_x_paa      (1'h0),	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:321:21]
    .io_x_eff      (1'h0),	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:321:21]
    .io_x_c        (1'h0),	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:321:21]
    .io_y_u        (/* unused */),
    .io_y_ae_ptw   (/* unused */),
    .io_y_ae_final (/* unused */),
    .io_y_pf       (/* unused */),
    .io_y_gf       (/* unused */),
    .io_y_sw       (/* unused */),
    .io_y_sx       (/* unused */),
    .io_y_sr       (/* unused */),
    .io_y_pw       (/* unused */),
    .io_y_px       (/* unused */),
    .io_y_pr       (/* unused */),
    .io_y_ppp      (/* unused */),
    .io_y_pal      (/* unused */),
    .io_y_paa      (/* unused */),
    .io_y_eff      (/* unused */),
    .io_y_c        (/* unused */)
  );
  assign io_resp_paddr = io_req_bits_vaddr[31:0];	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:644:23]
  assign io_resp_pf_inst = 1'h0;	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:321:21]
  assign io_resp_ae_inst = ~(legal_address & ({io_req_bits_vaddr[31], io_req_bits_vaddr[28:25], io_req_bits_vaddr[20], io_req_bits_vaddr[16], io_req_bits_vaddr[13:12]} == 9'h0 | {io_req_bits_vaddr[31], io_req_bits_vaddr[28:25], io_req_bits_vaddr[20], io_req_bits_vaddr[16], ~(io_req_bits_vaddr[13:12])} == 9'h0 | {io_req_bits_vaddr[31], io_req_bits_vaddr[28:25], io_req_bits_vaddr[20], ~(io_req_bits_vaddr[16])} == 7'h0 | {io_req_bits_vaddr[31], io_req_bits_vaddr[28], _GEN_0[11:9], io_req_bits_vaddr[20], io_req_bits_vaddr[16]} == 7'h0 | {_GEN[3], io_req_bits_vaddr[28]} == 2'h0) & ~(~io_ptw_status_debug & ~(|(io_req_bits_vaddr[33:12]))) & _pmp_io_x);	// @[generators/rocket-chip/src/main/scala/diplomacy/Parameters.scala:137:{31,41,46,59}, generators/rocket-chip/src/main/scala/rocket/TLB.scala:341:22, :405:19, :412:67, :420:{39,50}, :421:44, :426:65, :627:55, :635:23, generators/rocket-chip/src/main/scala/tilelink/Parameters.scala:616:89]
  assign io_resp_cacheable = legal_address & ({io_req_bits_vaddr[31], _GEN_0[11:10], io_req_bits_vaddr[16]} == 4'h0 | ~(_GEN[3]));	// @[generators/rocket-chip/src/main/scala/diplomacy/Parameters.scala:137:{31,41,46,59}, generators/rocket-chip/src/main/scala/rocket/TLB.scala:412:67, :415:19, generators/rocket-chip/src/main/scala/tilelink/Parameters.scala:616:89]
  assign io_ptw_req_bits_valid = ~io_kill;	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:653:28]
  assign io_ptw_req_bits_bits_addr = 21'h0;	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:343:25]
  assign io_ptw_req_bits_bits_need_gpa = 1'h0;	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:321:21]
  assign io_ptw_req_bits_bits_vstage1 = 1'h0;	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:321:21]
  assign io_ptw_req_bits_bits_stage2 = 1'h0;	// @[generators/rocket-chip/src/main/scala/rocket/TLB.scala:321:21]
endmodule

