// Generated by CIRCT firtool-1.61.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for prints and assertions.

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module TLSerdesser(
  input         clock,
                reset,
                auto_client_out_a_ready,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output        auto_client_out_a_valid,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [2:0]  auto_client_out_a_bits_opcode,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                auto_client_out_a_bits_param,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [3:0]  auto_client_out_a_bits_size,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [7:0]  auto_client_out_a_bits_source,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [31:0] auto_client_out_a_bits_address,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [7:0]  auto_client_out_a_bits_mask,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [63:0] auto_client_out_a_bits_data,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output        auto_client_out_a_bits_corrupt,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                auto_client_out_d_ready,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input         auto_client_out_d_valid,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [2:0]  auto_client_out_d_bits_opcode,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [1:0]  auto_client_out_d_bits_param,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [3:0]  auto_client_out_d_bits_size,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [7:0]  auto_client_out_d_bits_source,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [2:0]  auto_client_out_d_bits_sink,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input         auto_client_out_d_bits_denied,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [63:0] auto_client_out_d_bits_data,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input         auto_client_out_d_bits_corrupt,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output        io_ser_in_ready,	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:410:16]
  input         io_ser_in_valid,	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:410:16]
  input  [31:0] io_ser_in_bits,	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:410:16]
  input         io_ser_out_ready,	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:410:16]
  output        io_ser_out_valid,	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:410:16]
  output [31:0] io_ser_out_bits	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:410:16]
);

  wire        _inDes_io_out_valid;	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:440:23]
  wire [2:0]  _inDes_io_out_bits_chanId;	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:440:23]
  wire [7:0]  _inDes_io_out_bits_size;	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:440:23]
  wire [63:0] _inDes_io_out_bits_address;	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:440:23]
  wire [8:0]  _inDes_io_out_bits_union;	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:440:23]
  wire        _outSer_io_in_ready;	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:434:24]
  wire        _outArb_io_in_1_ready;	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:432:24]
  wire        _outArb_io_out_valid;	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:432:24]
  wire [2:0]  _outArb_io_out_bits_chanId;	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:432:24]
  wire [2:0]  _outArb_io_out_bits_opcode;	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:432:24]
  wire [2:0]  _outArb_io_out_bits_param;	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:432:24]
  wire [7:0]  _outArb_io_out_bits_size;	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:432:24]
  wire [7:0]  _outArb_io_out_bits_source;	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:432:24]
  wire [63:0] _outArb_io_out_bits_address;	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:432:24]
  wire [63:0] _outArb_io_out_bits_data;	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:432:24]
  wire        _outArb_io_out_bits_corrupt;	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:432:24]
  wire [8:0]  _outArb_io_out_bits_union;	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:432:24]
  wire        _outArb_io_out_bits_last;	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:432:24]
  wire [26:0] _merged_bits_last_beats1_decode_T_1 = 27'hFFF << auto_client_out_d_bits_size;	// @[generators/rocket-chip/src/main/scala/util/package.scala:235:71]
  wire [8:0]  merged_bits_last_beats1 = auto_client_out_d_bits_opcode[0] ? ~(_merged_bits_last_beats1_decode_T_1[11:3]) : 9'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:107:36, :222:14, :230:27, generators/rocket-chip/src/main/scala/util/package.scala:235:{46,71,76}]
  reg  [8:0]  merged_bits_last_counter_1;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27]
  always @(posedge clock) begin
    if (reset)
      merged_bits_last_counter_1 <= 9'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27]
    else if (_outArb_io_in_1_ready & auto_client_out_d_valid) begin	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:432:24, src/main/scala/chisel3/util/Decoupled.scala:52:35]
      if (merged_bits_last_counter_1 == 9'h0)	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27, :232:25]
        merged_bits_last_counter_1 <= merged_bits_last_beats1;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:222:14, :230:27]
      else	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:232:25]
        merged_bits_last_counter_1 <= merged_bits_last_counter_1 - 9'h1;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27, :231:28]
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:0];
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;
        merged_bits_last_counter_1 = _RANDOM[/*Zero width*/ 1'b0][17:9];	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  HellaPeekingArbiter outArb (	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:432:24]
    .clock                (clock),
    .reset                (reset),
    .io_in_0_bits_last    (1'h1),
    .io_in_1_ready        (_outArb_io_in_1_ready),
    .io_in_1_valid        (auto_client_out_d_valid),
    .io_in_1_bits_opcode  (auto_client_out_d_bits_opcode),
    .io_in_1_bits_param   ({1'h0, auto_client_out_d_bits_param}),	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:105:20]
    .io_in_1_bits_size    ({4'h0, auto_client_out_d_bits_size}),	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:106:20]
    .io_in_1_bits_source  (auto_client_out_d_bits_source),
    .io_in_1_bits_data    (auto_client_out_d_bits_data),
    .io_in_1_bits_corrupt (auto_client_out_d_bits_corrupt),
    .io_in_1_bits_union   ({5'h0, auto_client_out_d_bits_sink, auto_client_out_d_bits_denied}),	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:112:22]
    .io_in_1_bits_last    (merged_bits_last_counter_1 == 9'h1 | merged_bits_last_beats1 == 9'h0),	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:222:14, :230:27, :233:{25,33,43}]
    .io_in_2_bits_last    (1'h1),
    .io_in_3_bits_last    (1'h1),
    .io_in_4_ready        (/* unused */),
    .io_in_4_valid        (1'h0),
    .io_in_4_bits_opcode  (3'h0),	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:417:72]
    .io_in_4_bits_param   (3'h0),	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:417:72]
    .io_in_4_bits_size    (8'h0),	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:417:72]
    .io_in_4_bits_source  (8'h0),	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:417:72]
    .io_in_4_bits_address (64'h0),	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:417:72]
    .io_in_4_bits_data    (64'h0),	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:417:72]
    .io_in_4_bits_corrupt (1'h0),
    .io_in_4_bits_union   (9'h0),	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27]
    .io_in_4_bits_last    (1'h1),
    .io_out_ready         (_outSer_io_in_ready),	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:434:24]
    .io_out_valid         (_outArb_io_out_valid),
    .io_out_bits_chanId   (_outArb_io_out_bits_chanId),
    .io_out_bits_opcode   (_outArb_io_out_bits_opcode),
    .io_out_bits_param    (_outArb_io_out_bits_param),
    .io_out_bits_size     (_outArb_io_out_bits_size),
    .io_out_bits_source   (_outArb_io_out_bits_source),
    .io_out_bits_address  (_outArb_io_out_bits_address),
    .io_out_bits_data     (_outArb_io_out_bits_data),
    .io_out_bits_corrupt  (_outArb_io_out_bits_corrupt),
    .io_out_bits_union    (_outArb_io_out_bits_union),
    .io_out_bits_last     (_outArb_io_out_bits_last)
  );
  GenericSerializer outSer (	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:434:24]
    .clock              (clock),
    .reset              (reset),
    .io_in_ready        (_outSer_io_in_ready),
    .io_in_valid        (_outArb_io_out_valid),	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:432:24]
    .io_in_bits_chanId  (_outArb_io_out_bits_chanId),	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:432:24]
    .io_in_bits_opcode  (_outArb_io_out_bits_opcode),	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:432:24]
    .io_in_bits_param   (_outArb_io_out_bits_param),	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:432:24]
    .io_in_bits_size    (_outArb_io_out_bits_size),	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:432:24]
    .io_in_bits_source  (_outArb_io_out_bits_source),	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:432:24]
    .io_in_bits_address (_outArb_io_out_bits_address),	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:432:24]
    .io_in_bits_data    (_outArb_io_out_bits_data),	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:432:24]
    .io_in_bits_corrupt (_outArb_io_out_bits_corrupt),	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:432:24]
    .io_in_bits_union   (_outArb_io_out_bits_union),	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:432:24]
    .io_in_bits_last    (_outArb_io_out_bits_last),	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:432:24]
    .io_out_ready       (io_ser_out_ready),
    .io_out_valid       (io_ser_out_valid),
    .io_out_bits        (io_ser_out_bits)
  );
  GenericDeserializer inDes (	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:440:23]
    .clock               (clock),
    .reset               (reset),
    .io_in_ready         (io_ser_in_ready),
    .io_in_valid         (io_ser_in_valid),
    .io_in_bits          (io_ser_in_bits),
    .io_out_ready        (~(_inDes_io_out_bits_chanId == 3'h4 | _inDes_io_out_bits_chanId == 3'h3 | _inDes_io_out_bits_chanId == 3'h2 | _inDes_io_out_bits_chanId == 3'h1) & ~(|_inDes_io_out_bits_chanId) & auto_client_out_a_ready),	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:27:37, :124:20, :440:23, src/main/scala/chisel3/util/Mux.scala:77:13]
    .io_out_valid        (_inDes_io_out_valid),
    .io_out_bits_chanId  (_inDes_io_out_bits_chanId),
    .io_out_bits_opcode  (auto_client_out_a_bits_opcode),
    .io_out_bits_param   (auto_client_out_a_bits_param),
    .io_out_bits_size    (_inDes_io_out_bits_size),
    .io_out_bits_source  (auto_client_out_a_bits_source),
    .io_out_bits_address (_inDes_io_out_bits_address),
    .io_out_bits_data    (auto_client_out_a_bits_data),
    .io_out_bits_corrupt (auto_client_out_a_bits_corrupt),
    .io_out_bits_union   (_inDes_io_out_bits_union)
  );
  assign auto_client_out_a_valid = _inDes_io_out_valid & ~(|_inDes_io_out_bits_chanId);	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:27:37, :440:23, :443:45]
  assign auto_client_out_a_bits_size = _inDes_io_out_bits_size[3:0];	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:165:15, :440:23]
  assign auto_client_out_a_bits_address = _inDes_io_out_bits_address[31:0];	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:167:15, :440:23]
  assign auto_client_out_a_bits_mask = _inDes_io_out_bits_union[7:0];	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:173:15, :440:23]
  assign auto_client_out_d_ready = _outArb_io_in_1_ready;	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:432:24]
endmodule

