// Generated by CIRCT firtool-1.61.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for prints and assertions.

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module VectorScalarMultiplier_1(
  input         clock,
                reset,
  output        io_req_ready,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
  input         io_req_valid,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
  input  [31:0] io_req_bits_in_0,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
                io_req_bits_in_1,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
                io_req_bits_in_2,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
                io_req_bits_in_3,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
                io_req_bits_in_4,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
                io_req_bits_in_5,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
                io_req_bits_in_6,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
                io_req_bits_in_7,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
  input  [15:0] io_req_bits_repeats,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
  input         io_req_bits_last,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
  input  [12:0] io_req_bits_tag_addr,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
  input         io_req_bits_tag_mask_0,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
                io_req_bits_tag_mask_1,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
                io_req_bits_tag_mask_2,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
                io_req_bits_tag_mask_3,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
                io_req_bits_tag_mask_4,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
                io_req_bits_tag_mask_5,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
                io_req_bits_tag_mask_6,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
                io_req_bits_tag_mask_7,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
                io_req_bits_tag_mask_8,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
                io_req_bits_tag_mask_9,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
                io_req_bits_tag_mask_10,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
                io_req_bits_tag_mask_11,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
                io_req_bits_tag_mask_12,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
                io_req_bits_tag_mask_13,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
                io_req_bits_tag_mask_14,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
                io_req_bits_tag_mask_15,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
                io_req_bits_tag_mask_16,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
                io_req_bits_tag_mask_17,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
                io_req_bits_tag_mask_18,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
                io_req_bits_tag_mask_19,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
                io_req_bits_tag_mask_20,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
                io_req_bits_tag_mask_21,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
                io_req_bits_tag_mask_22,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
                io_req_bits_tag_mask_23,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
                io_req_bits_tag_mask_24,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
                io_req_bits_tag_mask_25,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
                io_req_bits_tag_mask_26,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
                io_req_bits_tag_mask_27,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
                io_req_bits_tag_mask_28,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
                io_req_bits_tag_mask_29,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
                io_req_bits_tag_mask_30,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
                io_req_bits_tag_mask_31,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
                io_req_bits_tag_is_acc,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
                io_req_bits_tag_accumulate,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
  input  [7:0]  io_req_bits_tag_bytes_read,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
                io_req_bits_tag_cmd_id,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
  input         io_resp_ready,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
  output        io_resp_valid,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
  output [31:0] io_resp_bits_out_0,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
                io_resp_bits_out_1,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
                io_resp_bits_out_2,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
                io_resp_bits_out_3,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
                io_resp_bits_out_4,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
                io_resp_bits_out_5,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
                io_resp_bits_out_6,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
                io_resp_bits_out_7,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
  output [15:0] io_resp_bits_row,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
  output        io_resp_bits_last,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
  output [12:0] io_resp_bits_tag_addr,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
  output        io_resp_bits_tag_mask_0,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
                io_resp_bits_tag_mask_1,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
                io_resp_bits_tag_mask_2,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
                io_resp_bits_tag_mask_3,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
                io_resp_bits_tag_mask_4,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
                io_resp_bits_tag_mask_5,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
                io_resp_bits_tag_mask_6,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
                io_resp_bits_tag_mask_7,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
                io_resp_bits_tag_mask_8,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
                io_resp_bits_tag_mask_9,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
                io_resp_bits_tag_mask_10,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
                io_resp_bits_tag_mask_11,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
                io_resp_bits_tag_mask_12,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
                io_resp_bits_tag_mask_13,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
                io_resp_bits_tag_mask_14,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
                io_resp_bits_tag_mask_15,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
                io_resp_bits_tag_mask_16,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
                io_resp_bits_tag_mask_17,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
                io_resp_bits_tag_mask_18,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
                io_resp_bits_tag_mask_19,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
                io_resp_bits_tag_mask_20,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
                io_resp_bits_tag_mask_21,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
                io_resp_bits_tag_mask_22,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
                io_resp_bits_tag_mask_23,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
                io_resp_bits_tag_mask_24,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
                io_resp_bits_tag_mask_25,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
                io_resp_bits_tag_mask_26,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
                io_resp_bits_tag_mask_27,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
                io_resp_bits_tag_mask_28,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
                io_resp_bits_tag_mask_29,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
                io_resp_bits_tag_mask_30,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
                io_resp_bits_tag_mask_31,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
                io_resp_bits_tag_is_acc,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
                io_resp_bits_tag_accumulate,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
  output [7:0]  io_resp_bits_tag_bytes_read,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
                io_resp_bits_tag_cmd_id	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
);

  wire        in_fire;	// @[src/main/scala/chisel3/util/Decoupled.scala:52:35]
  wire        _pipe_io_in_ready;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:83:22]
  reg         in_valid;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
  reg  [31:0] in_bits_in_0;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
  reg  [31:0] in_bits_in_1;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
  reg  [31:0] in_bits_in_2;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
  reg  [31:0] in_bits_in_3;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
  reg  [31:0] in_bits_in_4;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
  reg  [31:0] in_bits_in_5;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
  reg  [31:0] in_bits_in_6;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
  reg  [31:0] in_bits_in_7;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
  reg  [15:0] in_bits_repeats;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
  reg         in_bits_last;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
  reg  [12:0] in_bits_tag_addr;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
  reg         in_bits_tag_mask_0;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
  reg         in_bits_tag_mask_1;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
  reg         in_bits_tag_mask_2;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
  reg         in_bits_tag_mask_3;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
  reg         in_bits_tag_mask_4;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
  reg         in_bits_tag_mask_5;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
  reg         in_bits_tag_mask_6;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
  reg         in_bits_tag_mask_7;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
  reg         in_bits_tag_mask_8;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
  reg         in_bits_tag_mask_9;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
  reg         in_bits_tag_mask_10;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
  reg         in_bits_tag_mask_11;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
  reg         in_bits_tag_mask_12;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
  reg         in_bits_tag_mask_13;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
  reg         in_bits_tag_mask_14;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
  reg         in_bits_tag_mask_15;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
  reg         in_bits_tag_mask_16;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
  reg         in_bits_tag_mask_17;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
  reg         in_bits_tag_mask_18;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
  reg         in_bits_tag_mask_19;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
  reg         in_bits_tag_mask_20;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
  reg         in_bits_tag_mask_21;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
  reg         in_bits_tag_mask_22;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
  reg         in_bits_tag_mask_23;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
  reg         in_bits_tag_mask_24;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
  reg         in_bits_tag_mask_25;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
  reg         in_bits_tag_mask_26;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
  reg         in_bits_tag_mask_27;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
  reg         in_bits_tag_mask_28;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
  reg         in_bits_tag_mask_29;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
  reg         in_bits_tag_mask_30;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
  reg         in_bits_tag_mask_31;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
  reg         in_bits_tag_is_acc;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
  reg         in_bits_tag_accumulate;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
  reg  [7:0]  in_bits_tag_bytes_read;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
  reg  [7:0]  in_bits_tag_cmd_id;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
  wire        _pipe_io_in_bits_last_T = in_bits_repeats == 16'h0;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15, :67:49]
  wire        _io_req_ready_output = ~in_valid | _pipe_io_in_bits_last_T & in_fire;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15, :67:{19,29,49,57}, src/main/scala/chisel3/util/Decoupled.scala:52:35]
  assign in_fire = _pipe_io_in_ready & in_valid;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15, :83:22, src/main/scala/chisel3/util/Decoupled.scala:52:35]
  wire        _GEN = _io_req_ready_output & io_req_valid;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:67:29, src/main/scala/chisel3/util/Decoupled.scala:52:35]
  always @(posedge clock) begin
    if (reset)
      in_valid <= 1'h0;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
    else if (_GEN)	// @[src/main/scala/chisel3/util/Decoupled.scala:52:35]
      in_valid <= io_req_valid;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
    else	// @[src/main/scala/chisel3/util/Decoupled.scala:52:35]
      in_valid <= ~(in_fire & _pipe_io_in_bits_last_T) & in_valid;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15, :67:49, :72:25, :73:36, :74:16, src/main/scala/chisel3/util/Decoupled.scala:52:35]
    if (_GEN) begin	// @[src/main/scala/chisel3/util/Decoupled.scala:52:35]
      in_bits_in_0 <= io_req_bits_in_0;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
      in_bits_in_1 <= io_req_bits_in_1;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
      in_bits_in_2 <= io_req_bits_in_2;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
      in_bits_in_3 <= io_req_bits_in_3;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
      in_bits_in_4 <= io_req_bits_in_4;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
      in_bits_in_5 <= io_req_bits_in_5;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
      in_bits_in_6 <= io_req_bits_in_6;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
      in_bits_in_7 <= io_req_bits_in_7;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
      in_bits_repeats <= io_req_bits_repeats;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
      in_bits_last <= io_req_bits_last;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
      in_bits_tag_addr <= io_req_bits_tag_addr;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
      in_bits_tag_mask_0 <= io_req_bits_tag_mask_0;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
      in_bits_tag_mask_1 <= io_req_bits_tag_mask_1;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
      in_bits_tag_mask_2 <= io_req_bits_tag_mask_2;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
      in_bits_tag_mask_3 <= io_req_bits_tag_mask_3;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
      in_bits_tag_mask_4 <= io_req_bits_tag_mask_4;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
      in_bits_tag_mask_5 <= io_req_bits_tag_mask_5;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
      in_bits_tag_mask_6 <= io_req_bits_tag_mask_6;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
      in_bits_tag_mask_7 <= io_req_bits_tag_mask_7;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
      in_bits_tag_mask_8 <= io_req_bits_tag_mask_8;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
      in_bits_tag_mask_9 <= io_req_bits_tag_mask_9;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
      in_bits_tag_mask_10 <= io_req_bits_tag_mask_10;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
      in_bits_tag_mask_11 <= io_req_bits_tag_mask_11;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
      in_bits_tag_mask_12 <= io_req_bits_tag_mask_12;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
      in_bits_tag_mask_13 <= io_req_bits_tag_mask_13;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
      in_bits_tag_mask_14 <= io_req_bits_tag_mask_14;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
      in_bits_tag_mask_15 <= io_req_bits_tag_mask_15;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
      in_bits_tag_mask_16 <= io_req_bits_tag_mask_16;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
      in_bits_tag_mask_17 <= io_req_bits_tag_mask_17;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
      in_bits_tag_mask_18 <= io_req_bits_tag_mask_18;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
      in_bits_tag_mask_19 <= io_req_bits_tag_mask_19;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
      in_bits_tag_mask_20 <= io_req_bits_tag_mask_20;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
      in_bits_tag_mask_21 <= io_req_bits_tag_mask_21;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
      in_bits_tag_mask_22 <= io_req_bits_tag_mask_22;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
      in_bits_tag_mask_23 <= io_req_bits_tag_mask_23;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
      in_bits_tag_mask_24 <= io_req_bits_tag_mask_24;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
      in_bits_tag_mask_25 <= io_req_bits_tag_mask_25;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
      in_bits_tag_mask_26 <= io_req_bits_tag_mask_26;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
      in_bits_tag_mask_27 <= io_req_bits_tag_mask_27;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
      in_bits_tag_mask_28 <= io_req_bits_tag_mask_28;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
      in_bits_tag_mask_29 <= io_req_bits_tag_mask_29;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
      in_bits_tag_mask_30 <= io_req_bits_tag_mask_30;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
      in_bits_tag_mask_31 <= io_req_bits_tag_mask_31;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
      in_bits_tag_is_acc <= io_req_bits_tag_is_acc;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
      in_bits_tag_accumulate <= io_req_bits_tag_accumulate;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
      in_bits_tag_bytes_read <= io_req_bits_tag_bytes_read;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
      in_bits_tag_cmd_id <= io_req_bits_tag_cmd_id;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
    end
    else if (in_fire)	// @[src/main/scala/chisel3/util/Decoupled.scala:52:35]
      in_bits_repeats <= in_bits_repeats - 16'h1;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15, :76:40]
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:21];
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        for (logic [4:0] i = 5'h0; i < 5'h16; i += 5'h1) begin
          _RANDOM[i] = `RANDOM;
        end
        in_valid = _RANDOM[5'h0][0];	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
        in_bits_in_0 = {_RANDOM[5'h0][31:1], _RANDOM[5'h1][0]};	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
        in_bits_in_1 = {_RANDOM[5'h1][31:1], _RANDOM[5'h2][0]};	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
        in_bits_in_2 = {_RANDOM[5'h2][31:1], _RANDOM[5'h3][0]};	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
        in_bits_in_3 = {_RANDOM[5'h3][31:1], _RANDOM[5'h4][0]};	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
        in_bits_in_4 = {_RANDOM[5'h4][31:1], _RANDOM[5'h5][0]};	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
        in_bits_in_5 = {_RANDOM[5'h5][31:1], _RANDOM[5'h6][0]};	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
        in_bits_in_6 = {_RANDOM[5'h6][31:1], _RANDOM[5'h7][0]};	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
        in_bits_in_7 = {_RANDOM[5'h7][31:1], _RANDOM[5'h8][0]};	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
        in_bits_repeats = _RANDOM[5'h8][17:2];	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
        in_bits_last = _RANDOM[5'h8][26];	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
        in_bits_tag_addr = {_RANDOM[5'h10][31:27], _RANDOM[5'h11][7:0]};	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
        in_bits_tag_mask_0 = _RANDOM[5'h11][8];	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
        in_bits_tag_mask_1 = _RANDOM[5'h11][9];	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
        in_bits_tag_mask_2 = _RANDOM[5'h11][10];	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
        in_bits_tag_mask_3 = _RANDOM[5'h11][11];	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
        in_bits_tag_mask_4 = _RANDOM[5'h11][12];	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
        in_bits_tag_mask_5 = _RANDOM[5'h11][13];	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
        in_bits_tag_mask_6 = _RANDOM[5'h11][14];	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
        in_bits_tag_mask_7 = _RANDOM[5'h11][15];	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
        in_bits_tag_mask_8 = _RANDOM[5'h11][16];	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
        in_bits_tag_mask_9 = _RANDOM[5'h11][17];	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
        in_bits_tag_mask_10 = _RANDOM[5'h11][18];	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
        in_bits_tag_mask_11 = _RANDOM[5'h11][19];	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
        in_bits_tag_mask_12 = _RANDOM[5'h11][20];	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
        in_bits_tag_mask_13 = _RANDOM[5'h11][21];	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
        in_bits_tag_mask_14 = _RANDOM[5'h11][22];	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
        in_bits_tag_mask_15 = _RANDOM[5'h11][23];	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
        in_bits_tag_mask_16 = _RANDOM[5'h11][24];	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
        in_bits_tag_mask_17 = _RANDOM[5'h11][25];	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
        in_bits_tag_mask_18 = _RANDOM[5'h11][26];	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
        in_bits_tag_mask_19 = _RANDOM[5'h11][27];	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
        in_bits_tag_mask_20 = _RANDOM[5'h11][28];	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
        in_bits_tag_mask_21 = _RANDOM[5'h11][29];	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
        in_bits_tag_mask_22 = _RANDOM[5'h11][30];	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
        in_bits_tag_mask_23 = _RANDOM[5'h11][31];	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
        in_bits_tag_mask_24 = _RANDOM[5'h12][0];	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
        in_bits_tag_mask_25 = _RANDOM[5'h12][1];	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
        in_bits_tag_mask_26 = _RANDOM[5'h12][2];	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
        in_bits_tag_mask_27 = _RANDOM[5'h12][3];	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
        in_bits_tag_mask_28 = _RANDOM[5'h12][4];	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
        in_bits_tag_mask_29 = _RANDOM[5'h12][5];	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
        in_bits_tag_mask_30 = _RANDOM[5'h12][6];	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
        in_bits_tag_mask_31 = _RANDOM[5'h12][7];	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
        in_bits_tag_is_acc = _RANDOM[5'h12][8];	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
        in_bits_tag_accumulate = _RANDOM[5'h12][9];	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
        in_bits_tag_bytes_read = {_RANDOM[5'h14][31:28], _RANDOM[5'h15][3:0]};	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
        in_bits_tag_cmd_id = _RANDOM[5'h15][11:4];	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  Pipeline pipe (	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:83:22]
    .io_in_ready                (_pipe_io_in_ready),
    .io_in_valid                (in_valid),	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
    .io_in_bits_out_0           (in_bits_in_0),	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
    .io_in_bits_out_1           (in_bits_in_1),	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
    .io_in_bits_out_2           (in_bits_in_2),	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
    .io_in_bits_out_3           (in_bits_in_3),	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
    .io_in_bits_out_4           (in_bits_in_4),	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
    .io_in_bits_out_5           (in_bits_in_5),	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
    .io_in_bits_out_6           (in_bits_in_6),	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
    .io_in_bits_out_7           (in_bits_in_7),	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
    .io_in_bits_row             (in_bits_repeats),	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
    .io_in_bits_last            (_pipe_io_in_bits_last_T & in_bits_last),	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15, :67:49, :92:53]
    .io_in_bits_tag_addr        (in_bits_tag_addr),	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
    .io_in_bits_tag_mask_0      (in_bits_tag_mask_0),	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
    .io_in_bits_tag_mask_1      (in_bits_tag_mask_1),	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
    .io_in_bits_tag_mask_2      (in_bits_tag_mask_2),	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
    .io_in_bits_tag_mask_3      (in_bits_tag_mask_3),	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
    .io_in_bits_tag_mask_4      (in_bits_tag_mask_4),	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
    .io_in_bits_tag_mask_5      (in_bits_tag_mask_5),	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
    .io_in_bits_tag_mask_6      (in_bits_tag_mask_6),	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
    .io_in_bits_tag_mask_7      (in_bits_tag_mask_7),	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
    .io_in_bits_tag_mask_8      (in_bits_tag_mask_8),	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
    .io_in_bits_tag_mask_9      (in_bits_tag_mask_9),	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
    .io_in_bits_tag_mask_10     (in_bits_tag_mask_10),	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
    .io_in_bits_tag_mask_11     (in_bits_tag_mask_11),	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
    .io_in_bits_tag_mask_12     (in_bits_tag_mask_12),	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
    .io_in_bits_tag_mask_13     (in_bits_tag_mask_13),	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
    .io_in_bits_tag_mask_14     (in_bits_tag_mask_14),	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
    .io_in_bits_tag_mask_15     (in_bits_tag_mask_15),	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
    .io_in_bits_tag_mask_16     (in_bits_tag_mask_16),	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
    .io_in_bits_tag_mask_17     (in_bits_tag_mask_17),	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
    .io_in_bits_tag_mask_18     (in_bits_tag_mask_18),	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
    .io_in_bits_tag_mask_19     (in_bits_tag_mask_19),	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
    .io_in_bits_tag_mask_20     (in_bits_tag_mask_20),	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
    .io_in_bits_tag_mask_21     (in_bits_tag_mask_21),	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
    .io_in_bits_tag_mask_22     (in_bits_tag_mask_22),	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
    .io_in_bits_tag_mask_23     (in_bits_tag_mask_23),	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
    .io_in_bits_tag_mask_24     (in_bits_tag_mask_24),	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
    .io_in_bits_tag_mask_25     (in_bits_tag_mask_25),	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
    .io_in_bits_tag_mask_26     (in_bits_tag_mask_26),	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
    .io_in_bits_tag_mask_27     (in_bits_tag_mask_27),	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
    .io_in_bits_tag_mask_28     (in_bits_tag_mask_28),	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
    .io_in_bits_tag_mask_29     (in_bits_tag_mask_29),	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
    .io_in_bits_tag_mask_30     (in_bits_tag_mask_30),	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
    .io_in_bits_tag_mask_31     (in_bits_tag_mask_31),	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
    .io_in_bits_tag_is_acc      (in_bits_tag_is_acc),	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
    .io_in_bits_tag_accumulate  (in_bits_tag_accumulate),	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
    .io_in_bits_tag_bytes_read  (in_bits_tag_bytes_read),	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
    .io_in_bits_tag_cmd_id      (in_bits_tag_cmd_id),	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
    .io_out_ready               (io_resp_ready),
    .io_out_valid               (io_resp_valid),
    .io_out_bits_out_0          (io_resp_bits_out_0),
    .io_out_bits_out_1          (io_resp_bits_out_1),
    .io_out_bits_out_2          (io_resp_bits_out_2),
    .io_out_bits_out_3          (io_resp_bits_out_3),
    .io_out_bits_out_4          (io_resp_bits_out_4),
    .io_out_bits_out_5          (io_resp_bits_out_5),
    .io_out_bits_out_6          (io_resp_bits_out_6),
    .io_out_bits_out_7          (io_resp_bits_out_7),
    .io_out_bits_row            (io_resp_bits_row),
    .io_out_bits_last           (io_resp_bits_last),
    .io_out_bits_tag_addr       (io_resp_bits_tag_addr),
    .io_out_bits_tag_mask_0     (io_resp_bits_tag_mask_0),
    .io_out_bits_tag_mask_1     (io_resp_bits_tag_mask_1),
    .io_out_bits_tag_mask_2     (io_resp_bits_tag_mask_2),
    .io_out_bits_tag_mask_3     (io_resp_bits_tag_mask_3),
    .io_out_bits_tag_mask_4     (io_resp_bits_tag_mask_4),
    .io_out_bits_tag_mask_5     (io_resp_bits_tag_mask_5),
    .io_out_bits_tag_mask_6     (io_resp_bits_tag_mask_6),
    .io_out_bits_tag_mask_7     (io_resp_bits_tag_mask_7),
    .io_out_bits_tag_mask_8     (io_resp_bits_tag_mask_8),
    .io_out_bits_tag_mask_9     (io_resp_bits_tag_mask_9),
    .io_out_bits_tag_mask_10    (io_resp_bits_tag_mask_10),
    .io_out_bits_tag_mask_11    (io_resp_bits_tag_mask_11),
    .io_out_bits_tag_mask_12    (io_resp_bits_tag_mask_12),
    .io_out_bits_tag_mask_13    (io_resp_bits_tag_mask_13),
    .io_out_bits_tag_mask_14    (io_resp_bits_tag_mask_14),
    .io_out_bits_tag_mask_15    (io_resp_bits_tag_mask_15),
    .io_out_bits_tag_mask_16    (io_resp_bits_tag_mask_16),
    .io_out_bits_tag_mask_17    (io_resp_bits_tag_mask_17),
    .io_out_bits_tag_mask_18    (io_resp_bits_tag_mask_18),
    .io_out_bits_tag_mask_19    (io_resp_bits_tag_mask_19),
    .io_out_bits_tag_mask_20    (io_resp_bits_tag_mask_20),
    .io_out_bits_tag_mask_21    (io_resp_bits_tag_mask_21),
    .io_out_bits_tag_mask_22    (io_resp_bits_tag_mask_22),
    .io_out_bits_tag_mask_23    (io_resp_bits_tag_mask_23),
    .io_out_bits_tag_mask_24    (io_resp_bits_tag_mask_24),
    .io_out_bits_tag_mask_25    (io_resp_bits_tag_mask_25),
    .io_out_bits_tag_mask_26    (io_resp_bits_tag_mask_26),
    .io_out_bits_tag_mask_27    (io_resp_bits_tag_mask_27),
    .io_out_bits_tag_mask_28    (io_resp_bits_tag_mask_28),
    .io_out_bits_tag_mask_29    (io_resp_bits_tag_mask_29),
    .io_out_bits_tag_mask_30    (io_resp_bits_tag_mask_30),
    .io_out_bits_tag_mask_31    (io_resp_bits_tag_mask_31),
    .io_out_bits_tag_is_acc     (io_resp_bits_tag_is_acc),
    .io_out_bits_tag_accumulate (io_resp_bits_tag_accumulate),
    .io_out_bits_tag_bytes_read (io_resp_bits_tag_bytes_read),
    .io_out_bits_tag_cmd_id     (io_resp_bits_tag_cmd_id)
  );
  assign io_req_ready = _io_req_ready_output;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:67:29]
endmodule

